### ISSUE TITLE
Add examples for interacting with built-in numerics, and math ops like ceil/floor

### ISSUE THREAD

**Issue by rogusdev** [neogenie/fastnum#9]
e.g.
```
let a = UD128::from(-1i32);
let b = a + 2u128 / 3.4f64;
```

Also, examples for basic math operations like `round()`, ceil/floor (are these just `n.with_rounding_mode(RoundingMode::Ceiling).round(2)` etc?), and min/max (seems available as expected)?

Thanks! Compile time definition pulled me away from rust_decimal, but I would love to see comparison benchmarks with rust_decimal, even if that is performing better than fastnum within its supported range of features.

**Comment by rogusdev** [comment]
My current workaround:
```rust
    const THREE_ZEROES_REM: UD128 = THREE_ZEROES.rem(UD128::ONE);
    const FOUR_ZEROES_REM: UD128 = FOUR_ZEROES.rem(UD128::ONE);
    const FIVE_ZEROES_REM: UD128 = FIVE_ZEROES.rem(UD128::ONE);

    const THREE_ZEROES_CEIL: UD128 = THREE_ZEROES.sub(THREE_ZEROES_REM).add(UD128::ONE);
    const FOUR_ZEROES_CEIL: UD128 = FOUR_ZEROES.sub(FOUR_ZEROES_REM).add(UD128::ONE);
    const FIVE_ZEROES_CEIL: UD128 = FIVE_ZEROES.sub(FIVE_ZEROES_REM).add(UD128::ONE);
```

Those all come out, as I desire, to `2.0...` with the number of zeroes matching the precision they started with.

**Comment by rogusdev** [comment]
Turning the above into a fn (tho hopefully there is a more efficient solution possible internally -- along with fixing(/explaining?) rounding) and proving it with an even integer:

```rust
    const JUST_ONE: UD128 = udec128!(1.000);

    fn ceil(n: UD128) -> UD128 {
        let rem = n.rem(UD128::ONE);
        if rem > UD128::ZERO {
            n.sub(rem).add(UD128::ONE)
        } else {
            n
        }
    }

    println!(
        "{} vs {} vs {} vs {} -- {}",
        JUST_ONE,
        JUST_ONE
            .with_rounding_mode(RoundingMode::Ceiling)
            .round(0),
            JUST_ONE
            .with_rounding_mode(RoundingMode::Ceiling)
            .round(1),
            JUST_ONE
            .with_rounding_mode(RoundingMode::Ceiling)
            .round(2),
        ceil(JUST_ONE),
    );
```

**Comment by rogusdev** [comment]
Digging a bit into the code, I am decidedly suspicious of this: https://github.com/neogenie/fastnum/blob/b35b6a35d1c8d63d82d2ce1f21d551f701b8c15f/src/decimal/dec/extra_precision.rs#L37 but would still love an explanation.

It is also interesting to me that rem seems to depend on round: https://github.com/neogenie/fastnum/blob/b35b6a35d1c8d63d82d2ce1f21d551f701b8c15f/src/decimal/dec.rs#L1186 yet the rem approach seems to work, so perhaps I am just misunderstanding something critical about round. Which makes it extra important to document it with examples, probably! :)

**Comment by neogenie** [comment]
Hi, @rogusdev!

> But the current mixed middle ground does not make sense to me. Can you explain why that behavior is as it is?

It seems to be a bug, and it will be fixed asap in the next release!

I'll document it with extra examples and add more tests.

Stay tuned for updates.

**Comment by rogusdev** [comment]
Ok, I will try that in a bit, but to clarify: with those changes, how should I do `ceil` to the nearest integer given the entire decimal value, not just the previous position?

**Comment by neogenie** [comment]
All generally accepted rounding methods use only the next digit. The library previously used the cascading rounding method, but it is completely unintuitive and gives quite unpredictable results, so it was replaced with the standard one.

More about rounding modes: https://docs.rs/fastnum/latest/fastnum/#rounding

What problem are you trying to solve? Round `1.00000000000001` always to `2` ?

**Comment by rogusdev** [comment]
Yes, that makes sense which is why I am asking about `ceil` and not `round`.

https://doc.rust-lang.org/std/primitive.f64.html#method.ceil

**Comment by neogenie** [comment]
Got it!

I think we'll need a separate method for this. I'll research how it works in other decimal libraries and get back to you with a solution.

**Comment by neogenie** [comment]
@rogusdev 
Try pls https://docs.rs/fastnum/latest/fastnum/decimal/struct.Decimal.html#method.ceil

**Comment by rogusdev** [comment]
Hey, thanks, but I don't think that's how negatives are handled for ceil and floor:
https://math.stackexchange.com/questions/344815/how-do-the-floor-and-ceiling-functions-work-on-negative-numbers
And
https://doc.rust-lang.org/std/primitive.f64.html#method.floor

(Sadly, ceil does not have an official example of negative handling, but floor does)

**Comment by neogenie** [comment]
@rogusdev 

Khm...

Right now, this works exactly the same way as for standard f32 and f64 types:

```rust

use fastnum::*;

fn main() {
    // Ceil
    assert_eq!(3.01_f64.ceil(), 4.0);
    assert_eq!(dec256!(3.01).ceil(), dec256!(4));
    
    assert_eq!(3.99_f64.ceil(), 4.0);
    assert_eq!(dec256!(3.99).ceil(), dec256!(4));
    
    assert_eq!(4.0_f64.ceil(), 4.0);
    assert_eq!(dec256!(4.0).ceil(), dec256!(4));
    
    assert_eq!(1.0001_f64.ceil(), 2.0);
    assert_eq!(dec256!(1.0001).ceil(), dec256!(2));
    
    assert_eq!(1.00001_f64.ceil(), 2.0);
    assert_eq!(dec256!(1.00001).ceil(), dec256!(2));
    
    assert_eq!(1.000001_f64.ceil(), 2.0);
    assert_eq!(dec256!(1.000001).ceil(), dec256!(2));
    
    assert_eq!(1.00000000000001_f64.ceil(), 2.0);
    assert_eq!(dec256!(1.00000000000001).ceil(), dec256!(2));

    assert_eq!(-3.01_f64.ceil(), -4.0);
    assert_eq!(dec256!(-3.01).ceil(), dec256!(-4));
    
    assert_eq!(-3.5_f64.ceil(), -4.0);
    assert_eq!(dec256!(-3.5).ceil(), dec256!(-4));
    
    assert_eq!(-4.0_f64.ceil(), -4.0);
    assert_eq!(dec256!(-4.0).ceil(), dec256!(-4));
    
    // Floor
    assert_eq!(3.99_f64.floor(), 3.0);
    assert_eq!(dec256!(3.99).floor(), dec256!(3));
    
    assert_eq!(3.0_f64.floor(), 3.0);
    assert_eq!(dec256!(3.0).floor(), dec256!(3));
    
    assert_eq!(3.01_f64.floor(), 3.0);
    assert_eq!(dec256!(3.01).floor(), dec256!(3));
    
    assert_eq!(3.5_f64.floor(), 3.0);
    assert_eq!(dec256!(3.5).floor(), dec256!(3));
    
    assert_eq!(4.0_f64.floor(), 4.0);
    assert_eq!(dec256!(4.0).floor(), dec256!(4));
    
    assert_eq!(-3.01_f64.floor(), -3.0);
    assert_eq!(dec256!(-3.01).floor(), dec256!(-3));
    
    assert_eq!(-3.1_f64.floor(), -3.0);
    assert_eq!(dec256!(-3.1).floor(), dec256!(-3));
    
    assert_eq!(-3.5_f64.floor(), -3.0);
    assert_eq!(dec256!(-3.5).floor(), dec256!(-3));
    
    assert_eq!(-4.0_f64.floor(), -4.0);
    assert_eq!(dec256!(-4.0).floor(), dec256!(-4));
}

```

**Comment by rogusdev** [comment]
Ohhhhhhh, apparently it's operator precedence. The negative is applied to the result of the `.ceil()` rather than before.

So all your negative tests were testing the wrong value.

**Comment by neogenie** [comment]
Holy Saints!!! I feel like an idiot.  
Such strange behavior slightly confused me yesterday, but I couldn't manage this task...
Sorry, fixed in [v0.2.1](https://github.com/neogenie/fastnum/releases/tag/v0.2.1).

**Comment by rogusdev** [comment]
Thanks! I'm happy to close this issue as it became dominated by the one feature request, which is resolved now -- but the original spirit is still only partially addressed: I'd still recommend more examples that demonstrate interoperability between this library and basic rust types, along with demos of basic standard math operations.
